### ISSUE TITLE
Migrate Incubator app: Faucet

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-incubator#44]
Migrate the current Incubator Faucet application to this repository.
* Current source location: https://github.com/slateci/slate-catalog/tree/master/incubator/faucet/faucet
* New location: `./charts/faucet`

## Steps
1. Use this GitHub issue to create a feature branch.
2. Add the application to your feature branch.
3. Verify the image referenced in `deployment.yaml` is still published online.
4. Review the YAML files (lint, etc.)
5. Create the pull request linked back to this GitHub issue (at which point automatic linting and other checks will kick in).
6. Fix any remaining issues until the checks are all green.

**Comment by adamhgriffith-uofu** [comment]
It might also be worth double-checking that `ports` and other details in the chart match what is in the base image. E.g. if the base image has changed ports from `1234` to `5678` we'll need to update the chart to match.

**Comment by polinaLyubavina** [comment]
Migrated Faucet with https://github.com/slateci/slate-catalog-stable/pull/65 and https://github.com/slateci/slate-catalog-stable/pull/81
